#ifndef __controller_msgs__msg__QuixStairsStepType__idl__
#define __controller_msgs__msg__QuixStairsStepType__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {
      const octet FLAT =
      0;

      const octet UP =
      1;

      const octet DOWN =
      2;


      /**
       * This message is part of the Quix controller API.
       * This message is used to notify the controller of the user's desired stairs step type
       */
      @TypeCode(type="controller_msgs::msg::dds_::QuixStairsStepType_")
      struct QuixStairsStepType
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        @defaultValue(value=255)
        octet desired_stairs_step_type;
      };
    };
  };
};

#endif
